### ISSUE TITLE
create and expose types for subscription states

### ISSUE THREAD

**Issue by mason-fish** [docker/licensing#15]
As requested here, https://github.com/docker/cli/pull/1389#discussion_r220091980, let's add types for all of the subscription states so that they can be referred to more programmatically by consumers of this client lib.

**Comment by mason-fish** [comment]
fixed in https://github.com/docker/licensing/pull/17

**Comment by silvin-lubecki** [comment]
Can you update the docker/cli with the new exposed types (as suggested [here](https://github.com/docker/cli/pull/1389#discussion_r220091980)) ?
